Disable e2e [publish]

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -303,81 +303,81 @@ jobs:
   #                          medea-tag=${{ env.MEDEA_BRANCH }}
   #                          control-tag=build-${{ github.run_number }}
 
-  test-e2e-native:
-    name: test (E2E, ${{ matrix.platform }})
-    needs: ["build-jason", "build-jason-linux", "docker"]
-    strategy:
-      fail-fast: false
-      matrix:
-        # TODO: Run E2E test on Windows
-        platform:
-          - ios
-          - linux
-          - macos
-    runs-on: ${{ (contains('ios macos', matrix.platform) && 'macos-13')
-              || (matrix.platform == 'windows' &&           'windows-latest')
-              ||                                            'ubuntu-latest' }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: stable
-      - name: Setup Docker and Docker Compose
-        run: |
-          brew install colima docker docker-compose
-          colima start
-        if: ${{ contains('ios macos', matrix.platform) }}
+  # test-e2e-native:
+  #   name: test (E2E, ${{ matrix.platform }})
+  #   needs: ["build-jason", "build-jason-linux", "docker"]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # TODO: Run E2E test on Windows
+  #       platform:
+  #         - ios
+  #         - linux
+  #         - macos
+  #   runs-on: ${{ (contains('ios macos', matrix.platform) && 'macos-13')
+  #             || (matrix.platform == 'windows' &&           'windows-latest')
+  #             ||                                            'ubuntu-latest' }}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: dtolnay/rust-toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #     - name: Setup Docker and Docker Compose
+  #       run: |
+  #         brew install colima docker docker-compose
+  #         colima start
+  #       if: ${{ contains('ios macos', matrix.platform) }}
 
-      - uses: subosito/flutter-action@v2
-      - name: Install Flutter Linux dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-                       cmake \
-                       libgtk-3-dev liblzma-dev libpulse-dev \
-                       ninja-build pkg-config xvfb
-        if: ${{ matrix.platform == 'linux' }}
+  #     - uses: subosito/flutter-action@v2
+  #     - name: Install Flutter Linux dependencies
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install -y \
+  #                      cmake \
+  #                      libgtk-3-dev liblzma-dev libpulse-dev \
+  #                      ninja-build pkg-config xvfb
+  #       if: ${{ matrix.platform == 'linux' }}
 
-      - name: Start iOS simulator
-        id: simulator
-        uses: futureware-tech/simulator-action@v2
-        with:
-          os_version: '>=13.0'
-          os: iOS
-        if: ${{ matrix.platform == 'ios' }}
+  #     - name: Start iOS simulator
+  #       id: simulator
+  #       uses: futureware-tech/simulator-action@v2
+  #       with:
+  #         os_version: '>=13.0'
+  #         os: iOS
+  #       if: ${{ matrix.platform == 'ios' }}
 
-      - name: Download `medea-jason` lib
-        uses: actions/download-artifact@v3
-        with:
-          name: build-jason-${{ matrix.platform }}
-          path: ./flutter/${{ matrix.platform }}/lib/
+  #     - name: Download `medea-jason` lib
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: build-jason-${{ matrix.platform }}
+  #         path: ./flutter/${{ matrix.platform }}/lib/
 
-      - name: Download `medea-control-api-mock` Docker image
-        uses: actions/download-artifact@v3
-        with:
-          name: docker-medea-control-api-mock-${{ github.run_number }}
-          path: .cache/
-      - name: Unpack `medea-control-api-mock` Docker image
-        run: make docker.untar from-file=.cache/image.tar
+  #     - name: Download `medea-control-api-mock` Docker image
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: docker-medea-control-api-mock-${{ github.run_number }}
+  #         path: .cache/
+  #     - name: Unpack `medea-control-api-mock` Docker image
+  #       run: make docker.untar from-file=.cache/image.tar
 
-      - name: Login to Medea Docker registry
-        uses: docker/login-action@v2
-        with:
-          registry: hub.instrumentisto.com
-          username: ${{ secrets.MEDEA_DOCKER_USER }}
-          password: ${{ secrets.MEDEA_DOCKER_PASS }}
+  #     - name: Login to Medea Docker registry
+  #       uses: docker/login-action@v2
+  #       with:
+  #         registry: hub.instrumentisto.com
+  #         username: ${{ secrets.MEDEA_DOCKER_USER }}
+  #         password: ${{ secrets.MEDEA_DOCKER_PASS }}
 
-      - run: ${{ (matrix.platform == 'linux' && 'xvfb-run -a')
-              ||                                '' }}
-             make test.e2e.native
-                  device=${{ (matrix.platform == 'ios'
-                              && steps.simulator.outputs.udid)
-                          ||     matrix.platform }}
-                  up=yes debug=no dockerized=yes
-                  medea-tag=${{ env.MEDEA_BRANCH }}
-                  control-tag=build-${{ github.run_number }}
-             ${{ (matrix.platform == 'ios' && 'server=127.0.0.1 background=yes')
-              ||                              '' }}
+  #     - run: ${{ (matrix.platform == 'linux' && 'xvfb-run -a')
+  #             ||                                '' }}
+  #            make test.e2e.native
+  #                 device=${{ (matrix.platform == 'ios'
+  #                             && steps.simulator.outputs.udid)
+  #                         ||     matrix.platform }}
+  #                 up=yes debug=no dockerized=yes
+  #                 medea-tag=${{ env.MEDEA_BRANCH }}
+  #                 control-tag=build-${{ github.run_number }}
+  #            ${{ (matrix.platform == 'ios' && 'server=127.0.0.1 background=yes')
+  #             ||                              '' }}
 
   test-flutter:
     name: test (medea-jason, ${{ matrix.platform }})
